// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRwwflEcVQ-3UIVjJjMcIfv8gcRYvmDlM',
    appId: '1:202793020971:web:8dc4988e20b478716b846e',
    messagingSenderId: '202793020971',
    projectId: 'myportfolio-2ef92',
    authDomain: 'myportfolio-2ef92.firebaseapp.com',
    storageBucket: 'myportfolio-2ef92.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8RvCWAjEo1UGkF_SQG1FSs9TKJ4C7Hck',
    appId: '1:202793020971:android:12b0a558ce18175d6b846e',
    messagingSenderId: '202793020971',
    projectId: 'myportfolio-2ef92',
    storageBucket: 'myportfolio-2ef92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBySajFDDZQmjSOWrgQBs5nQQ-K-uisFP8',
    appId: '1:202793020971:ios:c0f3c2cfc133974a6b846e',
    messagingSenderId: '202793020971',
    projectId: 'myportfolio-2ef92',
    storageBucket: 'myportfolio-2ef92.appspot.com',
    iosClientId: '202793020971-r3i62eveh61bpmfqotm8np0brgo6t1s6.apps.googleusercontent.com',
    iosBundleId: 'com.johnny.app',
  );
}
